Add load_file performance benchmark tooling
astro-projects/astro pull request #105
Opened 2022-02-14 19:02 UTC by tatiana

2022-02-14 23:49 UTC, dimberman requested changes

2022-02-15 00:02 UTC, tatiana commented on tests/benchmark/dags/evaluate_load_file.py
> +        # table_xcom.set_downstream(aggregate_check)
Yes, I believe once the operator is working again, we should re-enable these lines. I believe it is relevant to make sure the load worked as expected for these larger datasets.

2022-02-15 00:02 UTC, tatiana commented on tests/benchmark/dags/evaluate_load_file.py
> +            chunksize=2000,
I'll play a bit with this and let you know how it goes!

2022-02-15 09:39 UTC, tatiana commented on tests/benchmark/README.md
> +        "path":"/tmp/covid_overview.csv",
Improve this - allow reproducibility by either adding a command to download these datasets or add them to a public GCS folder.

2022-02-15 09:55 UTC, tatiana commented on tests/benchmark/README.md
> +## Analyse the results
Add information related to the system where we obtained these results.

2022-02-15 10:49 UTC, tatiana commented on tests/benchmark/run.py
> +        io_counters_before = process.io_counters()._asdict()
MacOS doesn't have this :cry:

2022-02-15 10:49 UTC, tatiana commented on tests/benchmark/config-sample.json
> +        "path": "/home/tati/Data/title_ratings.csv",
At the moment this doesn't support relative paths - do we want to do this?

2022-02-15 10:49 UTC, tatiana commented on tests/benchmark/analyse.py
> +    mean_by_dag["memory_pss"] = mean_by_dag.memory_full_info_pss.apply(
In MacOS psutil does not expose PSS - so we should make this optional.

2022-02-15 10:49 UTC, tatiana commented on tests/benchmark/analyse.py
> +    mean_by_dag["memory_shared"] = mean_by_dag.memory_full_info_shared.apply(
In MacOS `psutil` also does not expose `memory_shared`

2022-02-15 13:17 UTC, tatiana commented on tests/benchmark/config-sample.json
> +        "path": "/home/tati/Data/title_ratings.csv",
It can be an improvement for the future!

2022-02-15 21:56 UTC, dimberman approved these changes

2022-02-17 13:09 UTC, merged